name: state_space_practice_gpu
channels:
- conda-forge
- nvidia
- franklab
- edeno
dependencies:
- python >=3.10,<3.13
- numpy
- scipy
- jaxlib=*=*cuda*
- jax
- pandas
- cuda-nvcc
- networkx
- xarray
- scikit-learn
- patsy
- tqdm
- track_linearization
- matplotlib
- seaborn
- ipython
- black
- pytest
- pytest-cov